use database::{DatabaseSubscriber, Subset};

use crate::database_content::*;

// `AliceAndBobSubset` is a subset of members that exists in the `MyDatabaseContent` struct
#[derive(Subset, Default, Clone, Copy)]
#[superset(MyDatabase)]
pub struct AliceAndBobSubset {
    alice: u8,
    bob: u16,
}

pub struct AliceAndBobSubscriber {}

// This subset implements the `DatabaseSubscriber` trait for the various types generated by the
// `Database` macro
impl DatabaseSubscriber<AliceAndBobSubset, MyDatabaseMember, MY_DATABASE_MEMBER_COUNT>
    for AliceAndBobSubscriber
{
    fn on_set(&self, change: &AliceAndBobSubset) {
        std::println!(
            "Alice or Bob changed! Alice: {}, Bob: {}",
            change.alice,
            change.bob
        );
    }
}
